---
- name: Use RAM for temporary file locations
  mount:
    state: present
    src: tmpfs
    path: "{{ item }}"
    fstype: tmpfs
    opts: nodev,nosuid
  loop:
    - /tmp
    - /var/log
    - /var/tmp
  tags:
    - fstab
    - mounts

- name: Use RAM for journald logs
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: Storage
    value: volatile
    backup: true
  tags:
    - systemd

- name: Decrease the swappiness level
  sysctl:
    sysctl_file: "{{ tmpfs_vm_swappiness_file }}"
    name: vm.swappiness
    value: "{{ tmpfs_vm_swappiness }}"
  tags:
    - sysctl
