---
- name: Install packages required for BtrFS backups
  package:
    state: present
    name: "{{ item }}"
  loop:
    - apt-btrfs-snapshot
    - make
    - python3-distutils

- name: Download grub-btrfs from GitHub
  git:
    repo: https://github.com/Antynea/grub-btrfs.git
    dest: /tmp/grub-btrfs

- name: Install grub-btrfs
  command: make install
  args:
    chdir: /tmp/grub-btrfs

- name: Change the GRUB menu name to 'Buttery Backups'
  lineinfile:
    path: /etc/default/grub-btrfs/config
    regexp: '^GRUB_BTRFS_SUBMENUNAME'
    line: 'GRUB_BTRFS_SUBMENUNAME="Buttery Backups"'
